Repository bounswe/bounswe2023group8, pull requests merged in 2023-11, with the labels that each got.

#333 Create m1_group8.md
  reports/m1_group8.md
Labels: priority: high

#368 WA-339
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/PostViewPage/index.tsx
Labels: status: in review, priority: low, type: new feature, in: frontend, effort: medium

#383 Implemented Geolocation View
  app/web/.env.development
  app/web/package.json
  app/web/src/components/Geolocation/LocationPicker.tsx
  app/web/src/hooks/useGeolocation.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/Follow/Follower/index.tsx
  app/web/src/pages/Follow/Following/index.tsx
  app/web/src/pages/MapTestPage/index.tsx
Labels: in: frontend

#385 Hotfix Router
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/MapTestPage/index.tsx
Labels: effort: low, in: frontend

#396 New IA page is implemented
  app/mobile/lib/modules/newIa/controllers/new_ia_controller.dart
  app/mobile/lib/modules/newIa/views/new_ia_view.dart
  app/mobile/pubspec.lock
Labels: in: mobile

#397 Several implementtions for post pages and geolocation
  app/web/src/components/Geolocation/LocationPicker.tsx
  app/web/src/components/Geolocation/LocationViewer.tsx
  app/web/src/components/Post/Create/PostCreateCard.tsx
  app/web/src/components/Post/Create/index.tsx
  app/web/src/components/Post/PostSmallPreview/PostPreviewCard.tsx
  app/web/src/hooks/usePost.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/MapTestPage/index.tsx
  app/web/src/pages/PostCreatePage/index.tsx
  app/web/src/pages/PostUpdatePage/index.tsx
  app/web/src/pages/PostViewPage/index.tsx
  app/web/src/pages/ProfilePage/index.tsx
Labels: in: frontend

#398 visitor interest area page added
  app/mobile/lib/modules/interestArea/views/visitor_ia.dart
  app/mobile/lib/modules/visitor_explore/controllers/visitor_explore_controller.dart
  app/mobile/lib/modules/visitor_explore/views/visitor_explore_view.dart
  app/mobile/lib/routes/app_pages.dart
  app/mobile/lib/routes/app_routes.dart
Labels: status: done, priority: high, effort: high, type: new feature, in: mobile, review required!

#430 Create lab_report_7.md
  reports/lab_report_7.md
Labels: in: wiki

#437 added interest area view
  app/web/src/mockData/milestone1/451_detailed_ia.json
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/InterestAreaCreatePage/index.tsx
  app/web/src/pages/InterestAreaViewPage/index.tsx
Labels: status: done, priority: low, type: new feature, in: frontend, effort: medium

#446 WA-444
  app/web/src/components/Post/DetailedPostCard.tsx
  app/web/src/mockData/milestone1/451_detailed_post.json
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/PostViewPage/index.tsx
Labels: type: improvement, status: done, priority: low, in: frontend, effort: medium

#456 Wa/web/feature/web bunch ia visitor page 382
  app/web/src/components/HomePagePost/HomePagePost.tsx
  app/web/src/components/Post/ModifiedPostPreviewCard.tsx
  app/web/src/components/User/User.tsx
  app/web/src/mockData/bunch_visitor_sample/451_bunch_tags.json
  app/web/src/mockData/bunch_visitor_sample/451_posts_visitor.json
  app/web/src/mockData/bunch_visitor_sample/451_related_bunches.json
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/BunchVisitorPage/index.tsx
  app/web/src/pages/TimelineHomePage/index.tsx
Labels: priority: high, effort: high, type: new feature, in: frontend

#472 Wa/web/feature/profile page crud 418
  app/web/src/components/Follow/Follower/FollowerModal.tsx
  app/web/src/components/Follow/Following/FollowingModal.tsx
  app/web/src/components/InterestArea/InterestAreaCard.tsx
  app/web/src/components/Layout/Sidebar/Sidebar.tsx
  app/web/src/components/Layout/Topbar/Topbar.tsx
  app/web/src/components/ProfileHeader/ProfileHeader.tsx
  app/web/src/contexts/AuthContext.tsx
  app/web/src/hooks/useProfile.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/ProfilePage/index.tsx
  app/web/src/pages/TimelineHomePage/index.tsx
Labels: in: frontend

#480 Post Create and View CRUDs implemented
  app/web/src/components/InterestArea/InterestAreaCard.tsx
  app/web/src/components/Post/Create/PostCreateCard.tsx
  app/web/src/components/Post/DetailedPostCard.tsx
  app/web/src/components/Post/PostSmallPreview/PostPreviewCard.tsx
  app/web/src/contexts/AuthContext.tsx
  app/web/src/hooks/usePost.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/InterestAreaViewPage/index.tsx
  app/web/src/pages/PostCreatePage/index.tsx
  app/web/src/pages/PostUpdatePage/index.tsx
  app/web/src/pages/PostViewPage/index.tsx
  app/web/src/pages/ProfilePage/index.tsx
  app/web/src/pages/TimelineHomePage/index.tsx
Labels: in: frontend

#481 Web master
  app/web/.env.development
  app/web/package.json
  app/web/public/assets/close.png
  app/web/src/components/Follow/Follower/FollowerCard.tsx
  app/web/src/components/Follow/Follower/FollowerModal.tsx
  app/web/src/components/Follow/Following/FollowingCard.tsx
  app/web/src/components/Follow/Following/FollowingModal.tsx
  app/web/src/components/Geolocation/LocationPicker.tsx
  app/web/src/components/Geolocation/LocationViewer.tsx
  app/web/src/components/InterestArea/InterestAreaCard.tsx
  app/web/src/components/InterestArea/InterestAreaCreateCard.tsx
  app/web/src/components/Layout/Sidebar/Sidebar.tsx
  app/web/src/components/Layout/Topbar/Topbar.tsx
  app/web/src/components/Post/Create/PostCreateCard.tsx
  app/web/src/components/Post/DetailedPostCard.tsx
  app/web/src/components/Post/ModifiedPostPreviewCard.tsx
  app/web/src/components/Post/PostPreviewCard.tsx
  app/web/src/components/Post/PostSmallPreview/PostPreviewCard.tsx
  app/web/src/components/ProfileDisplay/ProfileDisplay.tsx
  app/web/src/components/ProfileHeader/ProfileHeader.tsx
  app/web/src/contexts/AuthContext.tsx
  app/web/src/hooks/useGeolocation.tsx
  app/web/src/hooks/useInterestArea.tsx
  app/web/src/hooks/usePost.tsx
  app/web/src/hooks/useProfile.tsx
  app/web/src/hooks/useUser.tsx
  app/web/src/hooks/useWikiTags.tsx
  app/web/src/index.css
  app/web/src/mockData/bunch_visitor_sample/451_bunch_tags.json
  app/web/src/mockData/bunch_visitor_sample/451_posts_visitor.json
  app/web/src/mockData/bunch_visitor_sample/451_related_bunches.json
  app/web/src/mockData/milestone1/451_detailed_ia.json
  app/web/src/mockData/milestone1/451_detailed_post.json
  app/web/src/mockData/milestone1/451_tags.json
  app/web/src/mockData/milestone1/451_users.json
  app/web/src/mockData/milestone1/display1.svg
  app/web/src/mockData/milestone1/display2.svg
  app/web/src/mockData/milestone1/display3.svg
  app/web/src/mockData/milestone1/display4.svg
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/BunchVisitorPage/index.tsx
  app/web/src/pages/InterestAreaCreatePage/index.tsx
  app/web/src/pages/InterestAreaUpdatePage/index.tsx
  app/web/src/pages/InterestAreaViewPage/index.tsx
  app/web/src/pages/MapTestPage/index.tsx
  app/web/src/pages/PostCreatePage/index.tsx
  app/web/src/pages/PostUpdatePage/index.tsx
  app/web/src/pages/PostViewPage/index.tsx
  app/web/src/pages/ProfilePage/index.tsx
  app/web/src/pages/TimelineExplorePage/index.tsx
  app/web/src/pages/TimelineHomePage/index.tsx
  app/web/yarn.lock
Labels: in: frontend
