Repository bounswe/bounswe2023group8, pull requests merged in 2023-10, with the labels that each got.

#198 Create Lab Report Week #1
  reports/lab_report_1.md
Labels: status: in review, effort: low, in: wiki

#200 Fix Repository Structure
  .DS_Store
  .gitignore
  app/README.md
  app/backend/README.md
  app/mobile/README.md
  app/web/README.md
  deliverables/milestone1.md
Labels: type: improvement, status: in review, priority: low, effort: low

#245 Structure improvement
  app/web/.eslintrc.json
  app/web/package.json
  app/web/src/App.test.tsx
  app/web/src/App.tsx
  app/web/src/components/Layout/Sidebar/Sidebar.jsx
  app/web/src/components/Layout/Topbar/Topbar.jsx
  app/web/src/index.jsx
  app/web/src/pages/App/App.css
  app/web/src/pages/App/App.jsx
  app/web/src/pages/App/App.test.tsx
  app/web/src/pages/App/Router.jsx
  app/web/src/pages/OpeningPage/index.jsx
  app/web/src/pages/TemporaryRouterTestPages/PageWithNoWrapper/index.jsx
  app/web/src/pages/TemporaryRouterTestPages/PageWithTopbarAndSidebar/index.jsx
  app/web/src/pages/TemporaryRouterTestPages/PageWithTopbarOnly/index.jsx
  app/web/yarn.lock
Labels: effort: medium

#252 WA - 229 - Forgot Password Pages
  app/web/src/components/ConfirmNewPassword/ConfirmNewPassword.tsx
  app/web/src/components/ForgotPassword/ForgotPasswordModal.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/ConfirmNewPassword/index.tsx
  app/web/src/pages/ForgotPassword/index.tsx
Labels: priority: high, in: frontend

#278 Wa/web/feature/wrappers 274
  app/web/package.json
  app/web/src/components/ForgotPassword/ForgotPasswordModal.tsx
  app/web/src/components/Layout/Sidebar/Sidebar.jsx
  app/web/src/components/Layout/Sidebar/Sidebar.tsx
  app/web/src/components/Layout/Topbar/Topbar.jsx
  app/web/src/components/Layout/Topbar/Topbar.tsx
  app/web/src/components/Login/LoginModal.tsx
  app/web/src/components/Register/RegisterModal.tsx
  app/web/src/components/shared/SpanWithOnClick.tsx
  app/web/src/pages/App/App.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/ForgotPassword/index.tsx
  app/web/src/pages/Login/index.tsx
  app/web/src/pages/OpeningPage/index.jsx
  app/web/src/pages/OpeningPage/index.tsx
  app/web/src/pages/Register/index.tsx
  app/web/src/pages/TemporaryRouterTestPages/PageWithTopbarAndSidebar/index.jsx
  app/web/src/pages/TemporaryRouterTestPages/PageWithTopbarAndSidebar/index.tsx
  app/web/yarn.lock
Labels: in: frontend

#291 added interest area view to the profile page
  app/web/src/components/InterestArea/InterestAreaCard.tsx
  app/web/src/pages/App/Router.tsx
  app/web/src/pages/ProfilePage/index.tsx
Labels: type: new feature, in: frontend

#293 Wa/mobile/feature/follower pop up 266
  app/mobile/assets/icons/begumpp.jpeg
  app/mobile/lib/data/models/user_model.dart
  app/mobile/lib/modules/profile/controllers/followers_controller.dart
  app/mobile/lib/modules/profile/controllers/followings_controller.dart
  app/mobile/lib/modules/profile/views/profile_view.dart
Labels: in: mobile

#299 profile view finished
  app/mobile/assets/icons/notification.svg
  app/mobile/lib/data/constants/assets.dart
  app/mobile/lib/data/constants/palette.dart
  app/mobile/lib/data/models/ia_model.dart
  app/mobile/lib/data/models/post_model.dart
  app/mobile/lib/data/models/user_model.dart
  app/mobile/lib/data/widgets/post_list.dart
  app/mobile/lib/data/widgets/post_widget.dart
  app/mobile/lib/modules/bottom_navigation/controllers/bottom_navigation_controller.dart
  app/mobile/lib/modules/bottom_navigation/views/bottom_navigation_view.dart
  app/mobile/lib/modules/profile/controllers/followers_controller.dart
  app/mobile/lib/modules/profile/controllers/followings_controller.dart
  app/mobile/lib/modules/profile/controllers/profile_controller.dart
  app/mobile/lib/modules/profile/views/profile_view.dart
  app/mobile/lib/modules/profile/widgets/followers_popup.dart
  app/mobile/lib/modules/profile/widgets/followings_popup.dart
  app/mobile/lib/modules/profile/widgets/profile_header_widget.dart
Labels: in: mobile

#305 add JUnit tests to the backend project
  app/backend/enigma/pom.xml
  app/backend/enigma/src/main/java/com/wia/enigma/core/data/response/RegisterResponse.java
  app/backend/enigma/src/main/java/com/wia/enigma/core/service/EnigmaUserServiceImpl.java
  app/backend/enigma/src/main/java/com/wia/enigma/exceptions/GlobalExceptionHandler.java
  app/backend/enigma/src/main/java/com/wia/enigma/exceptions/custom/EnigmaConflictException.java
  app/backend/enigma/src/test/java/com/wia/enigma/EnigmaApplicationTests.java
  app/backend/enigma/src/test/java/com/wia/enigma/LogoutTests.java
  app/backend/enigma/src/test/java/com/wia/enigma/SigninTests.java
  app/backend/enigma/src/test/java/com/wia/enigma/SignupTests.java
  node_modules/.yarn-integrity
  yarn.lock
Labels: review required!
