Repository bounswe/bounswe2023group8, pull requests merged in 2023-05, with the labels that each got.

#140 Add Global Exception Handling to the Backend
  practice-app/server/src/main/java/com/bounswe/group8/exception/GlobalExceptionHandler.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/custom/AlreadyInUseException.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/custom/DuplicateResourceException.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/custom/PageException.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/custom/UnauthorizedException.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/response/ErrorResponse.java
  practice-app/server/src/main/resources/application.properties
Labels: type: improvement, status: in review, priority: low, effort: low, in: backend

#143 Add API Documentation to the Backend Project
  practice-app/server/pom.xml
  practice-app/server/src/main/resources/application.properties
Labels: type: improvement, status: in review, priority: high, effort: low, in: backend

#146 Pa 132
  practice-app/.idea/.gitignore
  practice-app/client/src/queries/begum.query.js
  practice-app/client/src/views/Begum.js
  practice-app/server/src/main/java/com/bounswe/group8/controller/WordController.java
  practice-app/server/src/main/java/com/bounswe/group8/model/FavouriteWord.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/AddFavRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/WordMeaningResponse.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/FavouriteWordDto.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/WordMeaningDto.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/FavouriteWordRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/service/WordService.java
Labels: priority: high

#147 [PA] Add Backend for Portfolio Management Section
  practice-app/server/src/main/java/com/bounswe/group8/controller/PostController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/StockController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/UserController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/WikiController.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/GlobalExceptionHandler.java
  practice-app/server/src/main/java/com/bounswe/group8/exception/custom/ApiRequestException.java
  practice-app/server/src/main/java/com/bounswe/group8/model/Stock.java
  practice-app/server/src/main/java/com/bounswe/group8/model/StockInfo.java
  practice-app/server/src/main/java/com/bounswe/group8/model/StockSearchKeyword.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/StockAutocompleteInfoDto.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/StockDto.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/request/PostCreateRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/request/UserCreateRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/response/AVGlobalQuoteResponse.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/response/AVSymbolSearchResponse.java
  practice-app/server/src/main/java/com/bounswe/group8/projections/StockAutocompleteProjection.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/StockInfoRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/StockRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/StockSearchKeywordRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/service/PostService.java
  practice-app/server/src/main/java/com/bounswe/group8/service/StockService.java
  practice-app/server/src/main/java/com/bounswe/group8/service/UserService.java
  practice-app/server/src/main/resources/application.properties
Labels: status: in progress, priority: high, effort: high, type: new feature, in: backend

#156 Front end of Wiki Api has been implemented.
  practice-app/client/package.json
  practice-app/client/src/queries/baki.query.js
  practice-app/client/src/views/Baki.js
Labels: effort: high

#155 [PA] New feature for Practice App: Storing location data
  .gitignore
  practice-app/client/.env
  practice-app/client/package-lock.json
  practice-app/client/package.json
  practice-app/client/src/components/Egemen/LocationForm.js
  practice-app/client/src/components/Egemen/LocationPicker.js
  practice-app/client/src/components/Egemen/LocationTable.js
  practice-app/client/src/queries/egemen.query.js
  practice-app/client/src/views/Egemen.js
  practice-app/server/src/main/java/com/bounswe/group8/controller/LocationController.java
  practice-app/server/src/main/java/com/bounswe/group8/mapper/LocationMapper.java
  practice-app/server/src/main/java/com/bounswe/group8/model/Location.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/LocationCreateRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/LocationDto.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/LocationRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/service/LocationService.java
  practice-app/server/src/test/java/com/bounswe/group8/Location/LocationControllerTest.java
  practice-app/server/src/test/java/com/bounswe/group8/Location/LocationServiceTest.java
Labels: status: in progress, priority: high, effort: high

#163 Pa 130
  practice-app/client/.idea/codeStyles/Project.xml
  practice-app/client/.idea/codeStyles/codeStyleConfig.xml
  practice-app/client/package-lock.json
  practice-app/client/src/components/Egemen/LocationForm.js
  practice-app/client/src/components/Meric/ForecastSearch.js
  practice-app/client/src/components/Meric/SavedLocations.js
  practice-app/client/src/queries/egemen.query.js
  practice-app/client/src/queries/meric.query.js
  practice-app/client/src/views/Egemen.js
  practice-app/client/src/views/Meric.js
  practice-app/server/src/main/java/com/bounswe/group8/controller/ForecastController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/LocationController.java
  practice-app/server/src/main/java/com/bounswe/group8/mapper/ForecastMapper.java
  practice-app/server/src/main/java/com/bounswe/group8/model/Forecast.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/ForecastCreateRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/ForecastDto.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/ForecastRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/service/ForecastService.java
  practice-app/server/src/main/java/com/bounswe/group8/service/LocationService.java
  practice-app/server/src/main/resources/application.properties
  practice-app/server/src/test/java/com/bounswe/group8/Location/LocationControllerTest.java
Labels: priority: high, effort: low

#145 [PA - 137] Number Search API Backend and Frontend
  .idea/runConfigurations.xml
  practice-app/client/src/views/Sude.js
  practice-app/server/pom.xml
  practice-app/server/src/main/java/com/bounswe/group8/controller/NumberSearchHistoryController.java
  practice-app/server/src/main/java/com/bounswe/group8/mapper/NumberSearchHistoryMapper.java
  practice-app/server/src/main/java/com/bounswe/group8/model/NumberSearchHistory.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/NumberSearchHistoryCreateRequest.java
  practice-app/server/src/main/java/com/bounswe/group8/payload/dto/NumberSearchHistoryDto.java
  practice-app/server/src/main/java/com/bounswe/group8/repository/NumberSearchHistoryRepository.java
  practice-app/server/src/main/java/com/bounswe/group8/service/NumberSearchHistoryService.java
Labels: priority: high

#175 Fix Overwritten Controller Code
  practice-app/server/src/main/java/com/bounswe/group8/controller/StarStockController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/StockController.java
  practice-app/server/src/main/java/com/bounswe/group8/controller/WikiController.java
  practice-app/server/src/main/java/com/bounswe/group8/service/StarStockService.java
  practice-app/server/src/main/java/com/bounswe/group8/service/StockService.java
  practice-app/server/src/main/java/com/bounswe/group8/service/WikiService.java
Labels: status: in review, priority: high, effort: high, type: new feature, in: backend

#177 Add Tests to Stock Controller
  practice-app/server/src/main/java/com/bounswe/group8/controller/StockController.java
  practice-app/server/src/test/java/com/bounswe/group8/stock/StockControllerTest.java
Labels: type: improvement, status: in review, priority: high, effort: low, in: backend
